name = "abogado-wilson"
# Worker definitivo para APIs y CORS
main = "cloudflare-final-worker.js"
compatibility_date = "2025-04-23"
# Usar variable de entorno para account_id en tiempo de despliegue
account_id = "f21b24d86935a055c03d21f7fffd1514" # Se recomienda configurar esto mediante --env durante el despliegue
workers_dev = true

# Configurar el worker como un módulo ES (no requiere build de assets)
[build.upload]
format = "modules"
dir = "."
main = "./cloudflare-final-worker.js"

# Configuración de KV y D1 Database
[[kv_namespaces]]
binding = "ABOGADO_WILSON_KV"
id = "d977cf29acc749ba8aeabbcb2d395cb3"

[[d1_databases]]
binding = "ABOGADO_WILSON_DB"
database_name = "abogado-wilson-db"
database_id = "f00d15a2-6069-4f19-a8eb-6f2217af2176"

# Configuración de entorno
[env.production]
name = "abogado-wilson"
routes = [
  "abogado-wilson.anipets12.workers.dev/*"
]

# Variables de entorno - NOTA: Las claves sensibles deben configurarse mediante la UI de Cloudflare o CLI
[vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "*"
API_ENABLED = "true"
SUPABASE_URL = "https://phzldiaohelbyobhjrnc.supabase.co"
# SUPABASE_KEY debe configurarse a través de variables secretas
CLIENT_VERSION = "3.0.0"
DISABLE_MULTIPLE_CLIENTS = "true"
N8N_WEBHOOK_URL = "https://n8nom.onrender.com/webhook/1cfd2baa-f5ec-4bc4-a99d-dfb36793eabd"
WHATSAPP_NUMBER = "+59398835269"
CONTACT_EMAIL = "Wifirmalegal@gmail.com"

# Secretos (para configurar mediante wrangler secret o la UI de Cloudflare)
# wrangler secret put SUPABASE_KEY
# wrangler secret put TURSO_AUTH_TOKEN
# wrangler secret put JWT_SECRET
# wrangler secret put CLOUDFLARE_API_TOKEN
# wrangler secret put N8N_API_KEY
# wrangler secret put TURNSTILE_SECRET_KEY
